# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LK_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LK_admin(object):
    def setupUi(self, LK_admin):
        LK_admin.setObjectName("LK_admin")
        LK_admin.resize(1076, 677)
        self.centralwidget = QtWidgets.QWidget(LK_admin)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 330, 321, 81))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 10, 181, 71))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        LK_admin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LK_admin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 21))
        self.menubar.setObjectName("menubar")
        LK_admin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LK_admin)
        self.statusbar.setObjectName("statusbar")
        LK_admin.setStatusBar(self.statusbar)

        self.retranslateUi(LK_admin)
        QtCore.QMetaObject.connectSlotsByName(LK_admin)

    def retranslateUi(self, LK_admin):
        _translate = QtCore.QCoreApplication.translate
        LK_admin.setWindowTitle(_translate("LK_admin", "MainWindow"))
        self.pushButton.setText(_translate("LK_admin", "OK"))
        self.label.setText(_translate("LK_admin", "Здарова АДМИН!"))
